### ISSUE TITLE
TPA's can be requested, but when accepted it says that there are no tp requests from that player.

### ISSUE THREAD

**Issue by karrotboi** [EternalFlame06/WarpUtils-Issues#10] opened 2024-07-21 06:48 UTC
### Bug Description

TPA's allow us to request a tpa, but when we try to accept it, it says that there are no tp requests. Also my base level permissions players have access to more than one home, when I have it set to one.
![2024-07-21_02 44 48](https://github.com/user-attachments/assets/96895b12-7bf3-4a1a-bd6a-3f3d11c5f812)

### Reproduction Steps

Installed into my mod folder of my mc server, it is 1.21

### Log File

In screenshot, nothing pops up in server console

**Comment by karrotboi** [comment] 2024-07-21 06:51
[crash-2024-07-21_02.49.47-server.txt](https://github.com/user-attachments/files/16323327/crash-2024-07-21_02.49.47-server.txt)
and the server crashed

**Comment by EternalFlame06** [comment] 2024-07-21 10:40
Thanks for the report. I think I already know what the error is.

**Comment by EternalFlame06** [comment] 2024-07-21 10:56
At least the server crash should be fixed in 0.3.1. I am not sure about the other problem, but I do not have a lot of time this week, so it may take a while till I can fix it.

**Comment by EternalFlame06** [comment] 2024-07-21 11:07
It seems like my code rework has caused a lot of bugs to occure.

**Comment by EternalFlame06** [comment] 2024-07-21 11:56
Should be fixed in 0.3.1 along with multiple other bugs. I couldn't reproduce the bug with the home count though.

**Comment by EternalFlame06** [comment] 2024-07-21 12:40
Btw have you changed the log level to see more in the logs?

**Comment by karrotboi** [comment] 2024-07-22 17:16
> Btw have you changed the log level to see more in the logs?

I have not, I am not sure how, I can do that for you though.

**Comment by karrotboi** [comment] 2024-07-22 22:23
> Its very simple, just use /warputils config general logLevel (value).
> 
> It just tells the console when some commands are used, it is not very thorough though when it comes to the features in the background.
> 
> Did the new version at least fix the bugs.

What log level should I put it to, I'll let you know when I update the mod, i haven't set up remote access for my server yet and I won't be by the computer for another few days, I can change the log level though.

**Comment by EternalFlame06** [comment] 2024-07-23 16:27
If you do update the mod just check if the bugs still persist, if they don't then great, if they do just set it to the highest level (4) and recreate the bug. Then check the console if anything interesting pops up. 

And then you could contact me again about it.

**Comment by karrotboi** [comment] 2024-07-23 20:41
> If you do update the mod just check if the bugs still persist, if they don't then great, if they do just set it to the highest level (4) and recreate the bug. Then check the console if anything interesting pops up. 
> 
> And then you could contact me again about it.

I'm back trying to fix my server computer (displays not working, etc). Once I'm done I should have a few players on to be able to test things out, and I'll be able to quickly give you responses because hopefully my remote access through a vpn that I'm setting up now I'll work.

**Comment by karrotboi** [comment] 2024-07-23 23:06
[crash-2024-07-22_19.31.23-server.txt](https://github.com/user-attachments/files/16355059/crash-2024-07-22_19.31.23-server.txt)

I'm about to start up the server with the new mod, this is the crash report from last night, chat gpt pointed me that it was warputils that broke it. I am installing the latest update now

**Comment by EternalFlame06** [comment] 2024-07-24 06:47
I guess I have messed something up in this version.

**Comment by EternalFlame06** [comment] 2024-07-24 10:41
Try to set the tpa duration to 0 (the duration is then infinite). This should circumvent the crash, because the server crashes when a tpa duration runs out.

I think I already have a solution, but when I can implement it, depends on when I have enough time.

**Comment by karrotboi** [comment] 2024-07-24 19:59
I'll do that before 7 pm est I promise! I have it set to like 5 seconds right now though.

**Comment by karrotboi** [comment] 2024-07-24 23:08
I didn't change the config file, but tpa command worked great! /back worked too.

**Closed** 2024-07-24 23:09 UTC
Labels: bug

**Comment by EternalFlame06** [comment] 2024-07-25 08:27
I missed that the crash report was for version 0.3.0 and not for the newest version and searched for the bug in the code that fixed the it ;). But I am glad that the bug is already fixed in the newest version, so setting the tpa duration to any other number you like without issue.
